---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - scaling.will-m-0.github.io
  resources:
  - mmcscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaling.will-m-0.github.io
  resources:
  - mmcscalers/finalizers
  verbs:
  - update
- apiGroups:
  - scaling.will-m-0.github.io
  resources:
  - mmcscalers/status
  verbs:
  - get
  - patch
  - update
